vich_uploader:
    db_driver: orm

    mappings:
        biens_image:
            uri_prefix: /images/immo
            upload_destination: '%kernel.project_dir%/public/images/immo'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_fonds:
            uri_prefix: /images/fonds
            upload_destination: '%kernel.project_dir%/public/images/fonds'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_logos:
            uri_prefix: /images/logos
            upload_destination: '%kernel.project_dir%/public/images/logos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_larges:
            uri_prefix: /images/larges
            upload_destination: '%kernel.project_dir%/public/images/larges'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        biens_rappelfonds:
            uri_prefix: /images/rappelfonds
            upload_destination: '%kernel.project_dir%/public/images/rappelfonds'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
